name = "Fatherless Goes To Nature"
author = "Veonise"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "17ce34a291135fb4990c44512015d3817579c14fc68050ba8187457ea1bf720f"

[versions]
fabric = "0.16.7"
minecraft = "1.20.1"

[options]
acceptable-game-versions = ["1.20.1"]
